version: '3.8'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile  # Укажите путь к вашему Dockerfile
    container_name: django
    ports:
      - "8000:8000"  # Укажите порт, на котором будет доступен ваш Django-проект
    volumes:
      - .:/app  # Монтируем текущую директорию в /app внутри контейнера
    depends_on:
      - redis  # Добавляем зависимость от сервиса Redis

  redis:
    image: redis:latest  # Используем официальный образ Redis
    container_name: redis
    ports:
      - "6379:6379"  # Укажите порт, на котором будет доступен Redis
